server:
  port: 8090
spring:
  data:
    mongodb:
      username: nemisolv
      password: nemisolv
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin