server:
  port: 8222
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: identity-service
          uri: lb:http://identity-service
          predicates:
            # if you want to use list of path, use comma instead of separating 2 lines (syntax -> so stranger )
#            - Path=/api/v1/auth/**,/oauth2/**
            - Path=${app.api-prefix}/identity/**,
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: lb:http://profile-service
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2


#        - id: customer-service
#          uri: lb:http://CUSTOMER-SERVICE
#          predicates:
#            - Path=/api/v1/customers/**
#        - id: order-service
#          uri: lb:http://ORDER-SERVICE
#          predicates:
#            - Path=/api/v1/orders/**
#        - id: order-lines-service
#          uri: lb:http://ORDER-SERVICE
#          predicates:
#            - Path=/api/v1/order-lines/**
        - id: product-service
          uri: lb:http://product-service
          predicates:
            - Path= ${app.api-prefix}/products/**
          filters:
              - StripPrefix=2
        - id: inventory-service
          uri: lb:http://inventory-service
          predicates:
            - Path= ${app.api-prefix}/inventories/**
          filters:
            - StripPrefix=2
#        - id: payment-service
#          uri: lb:http://PAYMENT-SERVICE
#          predicates:
#            - Path=/api/v1/payments/**


app:
  identity-url: http://localhost:8051/identity
  api-prefix: /api/v1


management:
  tracing:
    sampling:
      probability: 1.0