server:
  port: 8051
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_ecommerce_identity
    username: root
    password: nemisolv
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nemisolv
    password: kqtgsvxoqyonuiny
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: sendMailWithToken:net.nemisolv.identity.payload.auth.SendMailWithOtpToken



  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/bbf9aad6-5f58-4387-927e-02f0b07a72fa/v2.0
            user-name-attribute: name
        registration:
          azure:
            provider: azure
            client-id: 4a9d2591-57eb-4b88-8a56-f4950615b816
            client-secret: j028Q~7X9KmtTRjnfPiV4RqLFxNlQ09cg4iSLdo.
            authorization-grant-type: authorization_code
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - openid
              - email
              - profile
            client-name: Azure

          google:
            clientId: 108748481333-q03ovpcihsp67ngr7d3apam9feolosgv.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 1106813467180481
            clientSecret: 7ffa2355ccf06f28aee9c121909e45c7
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: Ov23lihBEakHgxjaQbcA
            clientSecret: c72fed7f34e7309ef098fe3ae31b20983f7ae477
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user

#          provider:
#            facebook:
#              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
#              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
#              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,picture






app:
  secure:
    auth_secret: tX+2LFhMcZjqog34U7OFc09SF/ijWXb7UrqABQ/RmD4=
    jwt:
      secretKey: MHQCAQEEIEYgBlyQVsH7SpHUH7x4RErcckhu7ary/JjhP72Nk19EoAcGBSuBBAAKoUQDQgAE1MtHIxlGP5TARqBccrddNm1FnYH1Fp+onETz5KbXPSeG5FGwKMUXGfAmSZJq2gENULFewwymt+9bTXkjBZhh8A==
      tokenExpireTime: 6000000000
      refreshTokenExpireTime: 100800000000
  mail:
    from: nemisolv@gmail.com
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

  ignored:
    urls:
      - /api/v1/auth/**

