server:
  port: 8051
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_ecommerce_identity
    username: root
    password: nemisolv
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nemisolv
    password: kqtgsvxoqyonuiny
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: sendMailWithToken:net.nemisolv.identity.payload.auth.SendMailWithOtpToken



  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/your-directory-id/v2.0
            user-name-attribute: name
        registration:
          azure:
            provider: azure
            client-id: your-client-id
            client-secret: your-client-secret
            authorization-grant-type: authorization_code
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - openid
              - email
              - profile
            client-name: Azure

          google:
            clientId: your-client-id
            clientSecret: your-client-secret
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
#



app:
  secure:
    auth_secret: tX+2LFhMcZjqog34U7OFc09SF/ijWXb7UrqABQ/RmD4=
    jwt:
      secretKey: MHQCAQEEIEYgBlyQVsH7SpHUH7x4RErcckhu7ary/JjhP72Nk19EoAcGBSuBBAAKoUQDQgAE1MtHIxlGP5TARqBccrddNm1FnYH1Fp+onETz5KbXPSeG5FGwKMUXGfAmSZJq2gENULFewwymt+9bTXkjBZhh8A==
      tokenExpireTime: 6000000000
      refreshTokenExpireTime: 100800000000
  mail:
    from: nemisolv@gmail.com
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

  ignored:
    urls:
      - /api/v1/auth/**

