server:
  port: 8040
spring:
  data:
    mongodb:
      username: nemisolv
      password: nemisolv
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.nemisolv.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.nemisolv.ecommerce.kafka.payment.PaymentConfirmation
  mail:
    host: smtp.gmail.com
    port: 587
    username: nemisolv
    password: kqtgsvxoqyonuiny
    properties:
      mail:
        smtp:
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
