package net.nemisolv.lib.core._enum;

public enum MailType {
    REGISTRATION_CONFIRMATION,
    PASSWORD_RESET,
    ORDER_CREATED_NOTIFICATION,
    ORDER_DELIVERED_NOTIFICATION,
    ORDER_CANCELLED_NOTIFICATION,
    PAYMENT_SUCCESS_NOTIFICATION,

}
