
services:
  mysql:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: nemisolv
      MYSQL_USER: nemisolv
      MYSQL_PASSWORD: nemisolv
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-ecommerce-network
  mongodb:
    image: mongo:8.0.4
    container_name: mongo_db
    ports:
      - 27018:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nemisolv
      - MONGO_INITDB_ROOT_PASSWORD=nemisolv

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=nemisolv
      - ME_CONFIG_MONGODB_ADMINPASSWORD=nemisolv
      - ME_CONFIG_MONGODB_SERVER=mongodb
  redis:
    image: redis:7.0.11
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - spring-ecommerce-network

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
        - "9411:9411"
    networks:
        - spring-ecommerce-network


networks:
  spring-ecommerce-network:
    driver: bridge
volumes:
  mysql-data:
  mongo:
