
services:
  mysql:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: nemisolv
      MYSQL_USER: nemisolv
      MYSQL_PASSWORD: nemisolv
      MYSQL_DATABASE: my_ecommerce_identity
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-ecommerce-network
  mongodb:
    image: mongo:8.0.4
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nemisolv
      - MONGO_INITDB_ROOT_PASSWORD=nemisolv

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=nemisolv
      - ME_CONFIG_MONGODB_ADMINPASSWORD=nemisolv
      - ME_CONFIG_MONGODB_SERVER=mongodb
  redis:
    image: redis:7.0.11
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - spring-ecommerce-network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - spring-ecommerce-network
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - spring-ecommerce-network

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
        - "9411:9411"
    networks:
        - spring-ecommerce-network


networks:
  spring-ecommerce-network:
    driver: bridge
volumes:
  mysql-data:
  mongo:
