spring:
  application:
   name:
    common-lib
  data:
    redis:
      host: localhost
      port: 6379


app:
  secure:
    jwt:
      secretKey: MHQCAQEEIEYgBlyQVsH7SpHUH7x4RErcckhu7ary/JjhP72Nk19EoAcGBSuBBAAKoUQDQgAE1MtHIxlGP5TARqBccrddNm1FnYH1Fp+onETz5KbXPSeG5FGwKMUXGfAmSZJq2gENULFewwymt+9bTXkjBZhh8A==
      tokenExpireTime: 6000000000
      refreshTokenExpireTime: 100800000000
  mail:
    from: nemisolv@gmail.com
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

  ignored:
    urls:
      - /api/v1/auth/**


